prise.o: sources/prise.c sources/prise.h sources/voyants.h
voyants.o: sources/voyants.c sources/voyants.h
baseclient.o: sources/baseclient.c sources/baseclient.h
installer_vehicule.o: sources/installer_vehicule.c \
 sources/installer_vehicule.h sources/log.h sources/borne.h \
 sources/voyants.h sources/timer.h sources/boutons.h sources/prise.h \
 sources/generateur.h sources/stop.h
generateur.o: sources/generateur.c sources/generateur.h sources/log.h
charger_batterie.o: sources/charger_batterie.c sources/charger_batterie.h \
 sources/borne.h sources/voyants.h sources/timer.h sources/boutons.h \
 sources/prise.h sources/generateur.h sources/stop.h sources/log.h
boutons.o: sources/boutons.c sources/boutons.h
borne.o: sources/borne.c sources/borne.h sources/voyants.h \
 sources/timer.h sources/boutons.h sources/prise.h sources/generateur.h \
 sources/stop.h sources/log.h sources/lecteurcarte.h sources/baseclient.h
lecteurcarte.o: sources/lecteurcarte.c sources/baseclient.h \
 sources/lecteurcarte.h sources/installer_vehicule.h \
 sources/charger_batterie.h sources/reprendre_vehicule.h sources/log.h \
 sources/borne.h sources/voyants.h sources/timer.h sources/boutons.h \
 sources/prise.h sources/generateur.h sources/stop.h
reprendre_vehicule.o: sources/reprendre_vehicule.c \
 sources/reprendre_vehicule.h sources/borne.h sources/voyants.h \
 sources/timer.h sources/boutons.h sources/prise.h sources/generateur.h \
 sources/stop.h sources/log.h
timer.o: sources/timer.c sources/timer.h
log.o: sources/log.c sources/log.h
stop.o: sources/stop.c sources/stop.h sources/boutons.h sources/log.h
